site_name: python-algorithm-workbook

nav:
  - 홈: index.md
  - 자료구조:
      - 소개: data_structure/intro.md
      - 스택: data_structure/stack.md

theme:
  name: material

  palette:
    primary: light green
    accent: purple

  font:
    text: Jua
    code: Ubuntu Mono

  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences