site_name: python-algorithm-workbook

nav:
  - Home: index.md


theme:
  name: material

  palette:
    primary: light green
    accent: purple

  font:
    text: Jua
    code: Ubuntu Mono

  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences